package yaml

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// TestKYAMLKubectlGoldens verifies that every golden file in
// testdata/kyaml/kubectl/ is conformant KYAML and is byte-identical to
// what the encoder produces when re-formatting it. This catches regressions
// against the corpus shipped in this repository.
//
// To regenerate the corpus against actual kubectl output, run:
//
//	make refresh-kyaml-corpus
//
// (requires a working kubectl + cluster context, with KYAML enabled).
func TestKYAMLKubectlGoldens(t *testing.T) {
	root := filepath.Join("testdata", "kyaml", "kubectl")
	matches, err := filepath.Glob(filepath.Join(root, "*.kyaml"))
	if err != nil {
		t.Fatalf("glob: %v", err)
	}
	if len(matches) == 0 {
		t.Skip("no kubectl golden files present; run scripts/refresh-kyaml-kubectl-corpus.sh to generate")
	}
	for _, path := range matches {
		t.Run(filepath.Base(path), func(t *testing.T) {
			golden, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("read %s: %v", path, err)
			}

			// 1. Strip the leading header comment (if present) so we
			// validate only the KYAML body.
			body := stripHeaderComment(golden)

			// 2. Body must be valid KYAML.
			if err := ValidateKYAML(body); err != nil {
				t.Errorf("golden %s is not valid KYAML:\n%s", path, FormatError(body, err))
				return
			}

			// 3. Format(body) must equal body exactly (idempotence — no
			// further normalization needed).
			reformatted, err := Format(body)
			if err != nil {
				t.Fatalf("Format %s: %v", path, err)
			}
			if !bytes.Equal(reformatted, body) {
				t.Errorf("golden %s drifted from canonical KYAML\n=== golden:\n%s=== reformatted:\n%s", path, body, reformatted)
			}
		})
	}
}

// TestKYAMLKubectlFixtureFormatting verifies that block-style YAML fixtures
// in testdata/kyaml/kubectl/_fixtures/ Format to the corresponding *.kyaml
// golden files. This is the conversion-correctness check.
func TestKYAMLKubectlFixtureFormatting(t *testing.T) {
	root := filepath.Join("testdata", "kyaml", "kubectl")
	fixtures, err := filepath.Glob(filepath.Join(root, "_fixtures", "*.yaml"))
	if err != nil {
		t.Fatalf("glob: %v", err)
	}
	if len(fixtures) == 0 {
		t.Skip("no kubectl fixtures present")
	}
	for _, fxt := range fixtures {
		t.Run(filepath.Base(fxt), func(t *testing.T) {
			src, err := os.ReadFile(fxt)
			if err != nil {
				t.Fatalf("read %s: %v", fxt, err)
			}

			// Find the corresponding .kyaml golden.
			base := filepath.Base(fxt)
			name := strings.TrimSuffix(base, filepath.Ext(base))
			goldenPath := filepath.Join(root, name+".kyaml")
			golden, err := os.ReadFile(goldenPath)
			if err != nil {
				t.Skipf("no golden for fixture %s", fxt)
			}
			expected := stripHeaderComment(golden)

			// Format the source into KYAML and compare.
			got, err := Format(src)
			if err != nil {
				t.Fatalf("Format %s: %v", fxt, err)
			}
			if !bytes.Equal(got, expected) {
				t.Errorf("Format(%s) does not match golden\n=== expected (%s):\n%s=== got:\n%s", fxt, goldenPath, expected, got)
			}
		})
	}
}

// stripHeaderComment removes a single leading run of "#"-prefixed comment
// lines from data, returning the body. Used to skip the "Generated by"
// header inserted by refresh-kyaml-kubectl-corpus.sh.
func stripHeaderComment(data []byte) []byte {
	lines := bytes.Split(data, []byte("\n"))
	i := 0
	for i < len(lines) && (len(lines[i]) == 0 || lines[i][0] == '#') {
		i++
	}
	return bytes.Join(lines[i:], []byte("\n"))
}
