TEST_SUITE_DIR := testdata/yaml-test-suite
TEST_SUITE_REPO := https://github.com/yaml/yaml-test-suite.git
TEST_SUITE_TAG := $(shell git ls-remote --tags $(TEST_SUITE_REPO) 'refs/tags/data-*' | grep -v '\^{}' | sed 's|.*refs/tags/||' | sort | tail -1)

# kubectl version against which the KYAML golden corpus was generated. Bump
# this intentionally with a CHANGELOG note when refreshing the corpus via
# `make refresh-kyaml-corpus`.
KUBECTL_VERSION := v1.34.0

# Fixtures applied to the cluster when refreshing the kubectl corpus, in
# "kind:resource-name" form (the resource name must match metadata.name in
# the corresponding _fixtures/<kind>.yaml file).
KYAML_KUBECTL_FIXTURES := \
	pod:kyaml-test-pod \
	deployment:kyaml-test-deployment \
	service:kyaml-test-service \
	configmap:kyaml-test-configmap \
	namespace:kyaml-test-ns

.PHONY: all clean clone-test-suite lint test test-acceptance test-bench \
        test-conformance test-fuzz test-mutation test-race \
        test-kyaml test-kyaml-acceptance test-kyaml-kubectl test-kyaml-fuzz \
        refresh-kyaml-corpus

all: clean clone-test-suite lint test test-acceptance test-bench \
     test-conformance test-fuzz test-mutation test-race \
     test-kyaml test-kyaml-acceptance test-kyaml-kubectl test-kyaml-fuzz

clean:
	@rm -rf $(TEST_SUITE_DIR) *.out test_mutation.json

clone-test-suite: $(TEST_SUITE_DIR)

$(TEST_SUITE_DIR):
	@git clone --quiet --branch $(TEST_SUITE_TAG) --depth 1 $(TEST_SUITE_REPO) $(TEST_SUITE_DIR)

lint:
	@test -z "$$(gofmt -l .)" || (echo "files not formatted:" && gofmt -l . && exit 1)
	go vet ./...
	go mod verify
	go tool golangci-lint run ./...
	go tool go-licenses check ./...
	go tool govulncheck ./...

test: clone-test-suite
	@go test -v -count=1 -coverprofile=test.out .
	@go tool cover -func=test.out | tail -1

test-acceptance:
	@go test -v -count=1 -run TestAcceptance -coverprofile=test_acceptance.out .
	@go tool cover -func=test_acceptance.out | tail -1

test-bench:
	@go test -bench=. -benchmem -count=1 . | tee test_bench.out

test-conformance: clone-test-suite
	@go test -v -count=1 -run TestYAMLTestSuite -coverprofile=test_conformance.out .
	@go tool cover -func=test_conformance.out | tail -1

test-fuzz:
	@go test -fuzz=FuzzUnmarshal -fuzztime=60s -run='^$$' .
	@go test -fuzz=FuzzScanner -fuzztime=60s -run='^$$' .
	@go test -fuzz=FuzzRoundTrip -fuzztime=60s -run='^$$' .
	@go test -fuzz=FuzzMarshalKYAML -fuzztime=60s -run='^$$' .
	@go test -fuzz=FuzzUnmarshalKYAML -fuzztime=60s -run='^$$' .
	@go test -fuzz=FuzzKYAMLRoundTrip -fuzztime=60s -run='^$$' .
	@go test -fuzz=FuzzValidKYAML -fuzztime=60s -run='^$$' .
	@go test -fuzz=FuzzFormatKYAML -fuzztime=60s -run='^$$' .

test-mutation: clone-test-suite
	@go tool github.com/go-gremlins/gremlins/cmd/gremlins unleash --config .gremlins.yaml

test-race:
	@go test -race -count=1 -coverprofile=test_race.out .
	@go tool cover -func=test_race.out | tail -1

# KYAML-specific test targets.
test-kyaml:
	@go test -v -count=1 -run 'TestKYAML' -coverprofile=test_kyaml.out .
	@go tool cover -func=test_kyaml.out | tail -1

test-kyaml-acceptance:
	@go test -v -count=1 -run 'TestKYAMLAcceptance' .

test-kyaml-kubectl:
	@go test -v -count=1 -run 'TestKYAMLKubectl' .

test-kyaml-fuzz:
	@go test -fuzz=FuzzMarshalKYAML -fuzztime=10s -run='^$$' .
	@go test -fuzz=FuzzUnmarshalKYAML -fuzztime=10s -run='^$$' .
	@go test -fuzz=FuzzKYAMLRoundTrip -fuzztime=10s -run='^$$' .
	@go test -fuzz=FuzzValidKYAML -fuzztime=10s -run='^$$' .
	@go test -fuzz=FuzzFormatKYAML -fuzztime=10s -run='^$$' .

# Regenerate testdata/kyaml/kubectl/ against a live kubectl + cluster.
# Requires kubectl >= 1.34 with KYAML enabled (KUBECTL_KYAML=true) and a
# working cluster context (e.g. via kind, minikube, or a real cluster).
# Bump KUBECTL_VERSION above when running this so the golden files record
# which kubectl release produced them.
refresh-kyaml-corpus:
	@command -v kubectl >/dev/null 2>&1 || { echo "error: kubectl not found in PATH" >&2; exit 2; }
	@KUBECTL_KYAML=true kubectl get --help 2>&1 | grep -q kyaml \
	    || { echo "error: kubectl does not support -o kyaml; need >= 1.34 with KUBECTL_KYAML=true" >&2; exit 3; }
	@mkdir -p testdata/kyaml/kubectl
	@kubectl apply -f testdata/kyaml/kubectl/_fixtures/ >/dev/null
	@sleep 2
	@for spec in $(KYAML_KUBECTL_FIXTURES); do \
	    kind=$${spec%%:*}; \
	    name=$${spec##*:}; \
	    out=testdata/kyaml/kubectl/$$kind.kyaml; \
	    printf '# Generated by `make refresh-kyaml-corpus` against kubectl %s.\n# Do not edit manually — re-run the target to refresh.\n' "$(KUBECTL_VERSION)" > $$out; \
	    KUBECTL_KYAML=true kubectl get $$kind $$name -o kyaml --ignore-not-found=false >> $$out \
	        || { echo "error: kubectl get $$kind $$name failed" >&2; exit 4; }; \
	    echo "wrote $$out"; \
	done
	@echo "Refreshed testdata/kyaml/kubectl for kubectl $(KUBECTL_VERSION)"
